name: Release (Packagist + TER)

on:
  push:
    tags:
      - "v*"
      - "*"

jobs:
  ter:
    name: Upload to TER
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload to TER
        uses: tomasnorre/typo3-upload-ter@v2
        with:
          api-token: ${{ secrets.TYPO3_API_TOKEN }}
          php-version: 8.3
